# This is a basic workflow to help you get started with Actions
name: deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only in the the master branch
  push:
    branches: [ main ]

env:
    PORT: 7001
    
jobs:

 test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 'Create env file'
          
        run: |
          echo "PORT=$PORT" >> .env
          echo "DB_URI=${{ secrets.DB_URI }}" >> .env
          cat .env
          
      
      - name: run npm install
        run: |
          cd server
          npm ci
          
      - name: run tests
      with: # Set the secret as an input
      DB_URI: ${{ secrets.DB_URI }}
    env: # Or as an environment variable
      PORT: ${{ secrets.PORT }}
        run: |
          cd server
          npm run test
 
#  build:
#     needs: test
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v2

#       - name: build
#         run: docker-compose build
      
#       - name: Login to Docker Hub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
      
#       - name: Push in Docker hub
#         run: docker-compose push